### ISSUE TITLE
Nothing playing, queue empty - upon adding song to queue via mobile app, no way to start playing from queue.

### ISSUE THREAD

**Issue by davidtakac** [IvicaDuspara/MeteorPlayer#2]
When we first start the player and load songs, nothing is playing. Mobile app connects to server and queues a song. The song doesn't start playing by itself and there is no way to make it play. 

Expected behavior: as soon as a song appears in queue, if nothing else was playing, autoplay it.

**Comment by IvicaDuspara** [comment]
If nothing is playing an a client queues an song, it will automatically start playing.
